# yamllint disable rule:line-length
name: charmed-pgbonuncer
base: core22
version: '1.21'
summary: PgBouncer in a snap.
description: |
  Lightweight connection pooler for PostgreSQL

architectures:
  - build-on: [amd64]
    build-for: [amd64]
  - build-on: [arm64]
    build-for: [arm64]
grade: stable
confinement: strict

system-usernames:
  snap_daemon: shared


package-repositories:
  - type: apt
    ppa: data-platform/pgbouncer
  - type: apt
    ppa: data-platform/pgbouncer-exporter

layout:
  /usr/lib/python3/dist-packages:
    bind: $SNAP/usr/lib/python3/dist-packages
  /etc/perl:
    bind: $SNAP/etc/perl
  /usr/local/lib/x86_64-linux-gnu/perl:
    bind: $SNAP/usr/local/lib/x86_64-linux-gnu/perl
  /usr/local/share/perl:
    bind: $SNAP/usr/local/share/perl
  /usr/lib/x86_64-linux-gnu/perl5:
    bind: $SNAP/usr/lib/x86_64-linux-gnu/perl5
  /usr/share/perl5:
    bind: $SNAP/usr/share/perl5
  /usr/lib/x86_64-linux-gnu/perl-base:
    bind: $SNAP/usr/lib/x86_64-linux-gnu/perl-base
  /usr/lib/x86_64-linux-gnu/perl:
    bind: $SNAP/usr/lib/x86_64-linux-gnu/perl
  /usr/share/perl:
    bind: $SNAP/usr/share/perl
  /usr/local/lib/site_perl:
    bind: $SNAP/usr/local/lib/site_perl

slots:
  logs:
    interface: content
    source:
      read:
        - $SNAP_COMMON/var/log/pgbouncer

apps:
  pgbouncer:
    command: usr/sbin/pgbouncer
  pgbouncer-server:
    command: start-pgbouncer.sh
    plugs:
      - network
      - network-bind
  prometheus-pgbouncer-exporter:
    command: start-pgb-exporter.sh
    plugs:
      - network
      - network-bind

parts:
  postgres-debs:
    plugin: nil
    stage-packages:
      - util-linux
      - pgbouncer=1.21.0-0ubuntu0.22.04.1~ppa1
      - golang-github-prometheus-community-pgbouncer-exporter=0.7.0-0ubuntu0.22.04.1~ppa1
      - locales-all
    organize:
      usr/share/doc/util-linux/copyright: licenses/COPYRIGHT-util-linux
      usr/share/doc/pgbouncer/copyright: licenses/COPYRIGHT-pgbouncer
      usr/share/doc/golang-github-prometheus-community-pgbouncer-exporter/copyright: licenses/COPYRIGHT-golang-github-prometheus-community-pgbouncer-exporter
      usr/share/doc/locales-all/copyright: licenses/COPYRIGHT-locales-all
  snap-license:
    plugin: dump
    source: .
    source-type: local
    stage:
      - licenses/LICENSE-snap
    organize:
      LICENSE: licenses/LICENSE-snap
  wrapper:
    plugin: dump
    source: snap/local
