#!/bin/bash

mkdir -p $SNAP_DATA/etc/pgbouncer
mkdir -p $SNAP_DATA/run/pgbouncer

mkdir -p $SNAP_COMMON/var/log/pgbouncer

chown -R 584788:root $SNAP_COMMON/*
chown -R 584788:root $SNAP_DATA/*
chmod -R 755 $SNAP_DATA/run/pgbouncer
